//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 0.0.0.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "0.0.0.0")]
	public enum AttackTypeName
	{
		Melee = 0,
		Ranged = 1,
		Spell = 2,
	}
}
