//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 0.0.0.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "0.0.0.0")]
	public enum AttributeName
	{
		Attack = 0,
		Defense = 1,
		MovementSpeed = 2,
		MaximumLife = 3,
		MaximumMana = 4,
		MaximumSpirit = 5,
		MaximumFury = 6,
		LifeRegeneration = 7,
		ResourceGeneration = 8,
		ResourceRegeneration = 9,
		ReducedManaCost = 10,
		ReducedSpiritCost = 11,
		ReducedFuryCost = 12,
		BlockChance = 13,
		DodgeChance = 14,
		IncreasedExperience = 15,
		LifeLeech = 16,
		FireResistance = 17,
		ColdResistance = 18,
		PoisonResistance = 19,
		LightningResistance = 20,
		AttackSpeed = 21,
		CriticalStrikeChance = 22,
		CriticalStrikeDamage = 23,
		PhysicalDamageReduction = 24,
		DamageReduction = 25,
		RangedDamageReduction = 26,
		MeleeDamageReduction = 27,
		NonPhysicalDamageReduction = 28,
		LifePerSecond = 29,
		CannotBeFrozen = 30,
		ReducedCooldownTime = 31,
		ReducedCcDuration = 32,
		IncreasedDamage = 33,
		IncreasedPhysicalDamage = 34,
		IncreasedColdDamage = 35,
		IncreasedFireDamage = 36,
		IncreasedLightningDamage = 37,
		IncreasedPoisonDamage = 38,
		IncreasedShoutDuration = 39,
		IncreasedFurySkillDamage = 40,
		IncreasedFurySkillCost = 41,
		IncreasedLife = 42,
		AllResistances = 43,
		ToAllRanks = 44,
		ToBarbRanks = 45,
		ToSorcRanks = 46,
		ToDruidRanks = 47,
		MagicFind = 48,
		GoldFind = 49,
		FasterCastRate = 50,
		MoreBleedingDamage = 51,
		AngelicPower = 52,
		DemonicPower = 53,
		AncestralPower = 54,
		ManaRegeneration = 55,
		SpiritRegeneration = 56,
		FuryRegeneration = 57,
		FuryGeneration = 58,
		ManaGeneration = 59,
		SpiritGeneration = 60,
	}
}
