//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 4.1.1229.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "4.1.1229.0")]
	public enum AttributeName
	{
		Attack = 0,
		Defense = 1,
		MovementSpeed = 2,
		MaximumLife = 3,
		MaximumResource = 4,
		LifeRegeneration = 5,
		ResourceGeneration = 6,
		ResourceRegeneration = 7,
		BlockChance = 8,
		DodgeChance = 9,
		IncreasedExperience = 10,
		LifeLeech = 11,
		FireResistance = 12,
		ColdResistance = 13,
		PoisonResistance = 14,
		LightningResistance = 15,
		AttackSpeed = 16,
		CriticalStrikeChance = 17,
		DamageReduction = 18,
		RangedDamageReduction = 19,
		MeleeDamageReduction = 20,
		NonPhysicalDamageReduction = 21,
		LifePerSecond = 22,
		CannotBeFrozen = 23,
		ReducedCooldownTime = 24,
		ReducedCcDuration = 25,
		IncreasedPhysicalDamage = 26,
		IncreasedDamage = 27,
		IncreasedShoutDuration = 28,
		IncreasedFurySkillDamage = 29,
		IncreasedFurySkillCost = 30,
		IncreasedLife = 31,
		AllResistances = 32,
		ToAllRanks = 33,
		ToBarbRanks = 34,
		ToSorcRanks = 35,
		ToDruidRanks = 36,
		MagicFind = 37,
		GoldFind = 38,
		FasterCastRate = 39,
		MoreBleedingDamage = 40,
	}
}
