//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 4.1.1229.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "4.1.1229.0")]
	public enum AttributeName
	{
		Attack = 0,
		Defense = 1,
		MovementSpeed = 2,
		MaximumLife = 3,
		MaximumResource = 4,
		LifeRegeneration = 5,
		ResourceGeneration = 6,
		ResourceRegeneration = 7,
		BlockChance = 8,
		DodgeChance = 9,
		IncreasedExperience = 10,
		LifeLeech = 11,
		FireResistance = 12,
		ColdResistance = 13,
		PoisonResistance = 14,
		LightningResistance = 15,
		AttackSpeed = 16,
		CriticalStrikeChance = 17,
		PhysicalDamageReduction = 18,
		DamageReduction = 19,
		RangedDamageReduction = 20,
		MeleeDamageReduction = 21,
		NonPhysicalDamageReduction = 22,
		LifePerSecond = 23,
		CannotBeFrozen = 24,
		ReducedCooldownTime = 25,
		ReducedCcDuration = 26,
		IncreasedPhysicalDamage = 27,
		IncreasedDamage = 28,
		IncreasedShoutDuration = 29,
		IncreasedFurySkillDamage = 30,
		IncreasedFurySkillCost = 31,
		IncreasedLife = 32,
		AllResistances = 33,
		ToAllRanks = 34,
		ToBarbRanks = 35,
		ToSorcRanks = 36,
		ToDruidRanks = 37,
		MagicFind = 38,
		GoldFind = 39,
		FasterCastRate = 40,
		MoreBleedingDamage = 41,
	}
}
