//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 0.0.0.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "0.0.0.0")]
	public enum DamageTypeName
	{
		Physical = 0,
		Fire = 1,
		Cold = 2,
		Lightning = 3,
		Poison = 4,
		Bleeding = 5,
	}
}
