//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 4.1.1229.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "4.1.1229.0")]
	public enum ItemBaseName
	{
		Boots = 0,
		Legs = 1,
		Gloves = 2,
		Chest = 3,
		Helmet = 4,
		Amulet = 5,
		Ring = 6,
		MainHand = 7,
		OffHand = 8,
		BothHands = 9,
	}
}
