//------------------------------------------------------------------------------
// <auto-generated>
// 	Generated by: EnumGenerator.Core - 0.0.0.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Hellforge.Core
{
	[GeneratedCode("EnumGenerator.Core", "0.0.0.0")]
	public enum ItemBaseName
	{
		All = 0,
		Boots = 1,
		Legs = 2,
		Gloves = 3,
		Chest = 4,
		Helmet = 5,
		Amulet = 6,
		Ring = 7,
		MainHand = 8,
		OffHand = 9,
		BothHands = 10,
	}
}
